language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install -r requirements.txt

script:
  - find ./homosphere -name \*.py -exec pylint -r yes {} \;
